language: rust
sudo: required

script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - gcc --version
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    alternatives:
      - alternative:
        name: gcc
        link: /usr/bin/gcc
        path: /usr/bin/gcc-5
        priority: 80

rust:
        - stable
matrix:
        fast_finish: true
cache : cargo
after_success:
        - cargo test;
env : RUSTFLAGS="$RUSTFLAGS -D warnings"
before_deploy:
        - rustup install nightly
        - cargo +nightly doc
        - cp -r target/doc public/
        - pwd
        - ls
        - echo "<meta http-equiv=refresh content=0;url=librobot/index.html>" > public/index.html
        - echo $GITHUB_TOKEN
deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: false
        local-dir: public
        target-branch: gh-pages
        repo: ClubRobotInsat/librobot
        project-name: Documentation Librobot
        on:
                branch: master
notifications:
          email: false
