[package]
authors = ["Paul Florence <florencepaul@hotmail.fr>"]
name = "librobot"
version = "0.1.0"

[dependencies]
embedded-hal = "0.2.1"
nb = "0.1.1"

[dependencies.arrayvec]
default-features = false
features = []
version = "0.4.7"
